openapi: 3.0.0
info:
  title: Greeter
  description: Simple API to greet using a submodule
  version: 1.0.0
paths:
  /greeter:
    get:
      summary: Greeter Endpoint
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      operationId: getGreeting
